Bekhar/Models/Kala.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bekhar.Models
{
    public class Kala : ElasticDocument
    {

        [Display(Name = "عنوان کالا")]
        [Required(ErrorMessage = "وارد کردن عنوان ضروری است.")]
        public string Name { get; set; }

        [Display(Name = "توضیحات کالا")]
        public string Description { get; set; }

        [Display(Name = "قیمت کالا")]
        public long? Price { get; set; }
        [Display(Name = "موبایل")]
        public string Mobile { get; set; }

        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "وارد کردن ایمیل ضروری است.")]
        [EmailAddress(ErrorMessage = "ایمیل نامعتبر")]
        public string Email { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        public DateTime CreationTime { get; set; }
        public string Category { get; set; }

        [Display(Name = "شهر")]
        public string City { get; set; }

        [Display(Name = "محله")]
        public string Location { get; set; }

        public string Username { get; set; }

        public HttpPostedFileBase file { get; set; }

        public DateTime? Deadline { get; set; }

        [JsonIgnore]
        public long? DeadlineTimeStamp => ((Nullable<DateTimeOffset>)Deadline)?.ToUnixTimeMilliseconds();

        [Display(Name="تاریخ پایان مزایده")]
        public string DeadlineDate { get; set; }

        [Display(Name = "زمان پایان مزایده")]
        public string DeadlineTime { get; set; }

        public string IsTabligh { get; set; }

        public ModelType DataType { get; set; } = ModelType.Kala;

        //public Mozayede ConvertToMozayede()
        //{
        //    return new Mozayede()
        //    {
        //        Id = Id,
        //        Category = Category,
        //        City = City,
        //        CreationTime = CreationTime,
        //        DataType = DataType,
        //        Description = Description,
        //        Email = Email,
        //        Location = Location,
        //        Mobile = Mobile,
        //        Name = Name,
        //        Price = Price,
        //        Username = Username
        //    };
        //}
    }
}

Bekhar/Controllers/KalaController.cs
using Bekhar.Elastic;
using Bekhar.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bekhar.Controllers
{
    [Authorize]
    public class KalaController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Kala
        public ActionResult Index()
        {
            var searchParam = new SearchParameter()
            {
                Username = User.Identity.Name
            };

            List<Kala> items = ElasticEngine.GetKalaBySearchParam(searchParam);
            return View(items);
        }

        // GET: Kala/Details/5
        [AllowAnonymous]
        public ActionResult Details(string id)
        {
            var showUser = !string.IsNullOrEmpty(User.Identity.Name);
            Kala item = GetKala(id, UserManager, showUser);

            return View(item);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult GetCategoryByParentId(string id)
        {
            if (string.IsNullOrEmpty(id))
                return Json(Utility.GetAllCategories());
            else
                return Json(Utility.GetCategoryByParentId(Convert.ToInt32(id)));
        }

        public static Kala GetKala(string id, ApplicationUserManager userManager, bool showUser = true)
        {
            Kala item = ElasticEngine.GetKalaById(id);

            if (int.TryParse(item.Category, out var catId))
                item.Category = Utility.GetCategoryById(catId).Name;

            if (showUser)
            {
                var user = userManager.FindByNameAsync(item.Username).Result;
                item.Mobile = user.PhoneNumber;
                item.Email = user.Email;
            }
            else
            {
                item.Mobile = "وارد شوید";
                item.Email = "وارد شوید";
            }

            item.Id = id;
            return item;
        }

        // GET: Kala/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kala/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price,Location,City,Category,DeadlineDate,DeadlineTime,IsTabligh")] Kala kala)
        {
            // TODO ولیدیشن ها چک شوند
            //if (ModelState.IsValid)
            {
                kala.Username = User.Identity.Name;
                kala.CreationTime = DateTime.Now;

                if (kala.file != null)
                {
                    var fileName = System.Guid.NewGuid().ToString() + System.IO.Path.GetExtension(kala.file.FileName);
                    string physicalPath = Server.MapPath("~/Images/Uploads" + fileName);
                    // save image in folder
                    kala.file.SaveAs(physicalPath);
                }

                if (kala.IsTabligh == "true")
                {
                    var money = GetUserMoney(User.Identity.Name);

                    if (!HaveEnoughMoney(kala.Price.Value, User.Identity.Name))
                        return RedirectToAction("Create", "Transaction", null);

                    var transaction = new Transaction()
                    {
                        Amount = -5000,
                        Purpose = PurposeType.Tabligh,
                        Username = User.Identity.Name,
                        CreationTime = DateTime.Now,
                    };

                    ElasticEngine.AddTranasction(transaction);
                    KharidsController.ChangeUserMoney(User.Identity.Name, Math.Abs(transaction.Amount), false);
                }

                if (string.IsNullOrWhiteSpace(kala.DeadlineDate))
                    ElasticEngine.AddKala(kala);
                else
                {
                    kala.DataType = ModelType.Mozayede;
                    kala.Deadline = Convert.ToDateTime(kala.DeadlineDate);
                    if (!string.IsNullOrWhiteSpace(kala.DeadlineTime))
                    {
                        var time = kala.DeadlineTime.Split(':').Select(x => Convert.ToInt32(x)).ToList();
                        kala.Deadline?.Add(new TimeSpan(time[0], time[1], 0));
                    }

                    ElasticEngine.AddKala(kala);
                }

                return RedirectToAction("Index", "Home", null);
            }
        }

        private bool HaveEnoughMoney(long price, string username)
        {
            var money = GetUserMoney(username);

            if (price > money)
                return false;

            return true;
        }
        public long GetUserMoney(string userName)
        {
            return UserManager.FindByNameAsync(userName).Result.Money;
        }

        // GET: Kala/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Kala/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Kala/Delete/5
        public ActionResult Delete(string id)
        {
            Kala item = ElasticEngine.GetKalaById(id);

            if (int.TryParse(item.Category, out var catId))
                item.Category = Utility.GetCategoryById(catId).Name;

            return View(item);
        }

        // POST: Kala/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                Kala item = ElasticEngine.GetKalaById(id);
                if (item.Username == User.Identity.Name)
                    ElasticEngine.DeleteKala(id);
                else
                    throw new InvalidOperationException("Access is deneied");

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Bekhar/Views/Kala/Create.cshtml
@model Bekhar.Models.Kala

@{
    Page.Title = "ثبت آگهی جدید";
    Page.CustomCSS = "~/Content/css/create_kala.css";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <h3 class="text-center py-3 my-1 grey-text">
            ثبت آگهی جدید
        </h3>

        <div class="jumbotron">
            <div class="row">
                <div class="col-7">
                    <div class="form-group">
                        <label for="adTitle">عنوان آگهی</label>
                        <input type="text" class="form-control" name="Name">
                    </div>
                </div>
                <div class="col-3">
                    <label for="category">دسته بندی</label>
                    <div class="input-group">
                        <select class="browser-default custom-select" id="category" name="Category">
                            @*<input type="hidden" value="" id="adCategory" name="Category" />
                                <script>
                                    function updateCat(selectedCat)
                                    {
                                        // alert(JSON.stringify(data));
                                        // alert($("#category").children("option:selected").attr("value"));

                                        $("#adCategory").attr("value", selectedCat);//$("#category").children("option:selected").attr("value"));

                                        //if ($("#adCategory").attr("value") === null)
                                        //{
                                        //    $("#adCategory").attr("value", "")
                                        //}

                                        $.ajax({
                                        method: "POST",
                                        url: "/Kala/GetCategoryByParentId",
                                        data: { "id": selectedCat },
                                        success: function (result)
                                        {
                                            $("#category").html("");
                                            for (var i = 0; i < result.length; i++)
                                            {
                                                var cat = result[i];
                                                $("#category").append("<option value='" + cat.id + "'>" + cat.Name + "</option>");
                                            }
                                        },
                                        error: function (result)
                                        {
                                            alert(result.status);
                                        }
                                        });

                                    }
                                    $(document).ready(function () {
                                    updateCat("");
                                    });
                                </script>

                                <select class="browser-default custom-select" id="category" onchange="alert($(this).val);" >*@

                            <option value="" selected disabled>دسته بندی کالا را انتخاب کنید</option>
                            @{
                                var categories = Bekhar.Models.Utility.GetAllCategories();
                            }
                            @foreach (var category in categories)
                            {
                                <option value="@category.Id.ToString()">@category.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label for="mozToggle">
                            مزایده
                        </label>
                        <div class="input-group">
                            <label class="switch">
                                <input type="checkbox" class="primary" onchange="toggleMozayede(this);" id="mozToggle">
                                <span class="slider"></span>
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="mozToggle">
                            تبلیغ در سامانه
                        </label>
                        <div class="input-group">
                            <label class="switch">
                                <input type="hidden" id="adTabligh" name="IsTabligh" />
                                <input type="checkbox" class="primary" onchange="toggleTabligh(this);">
                                <span class="slider"></span>
                            </label>
                        </div>
                    </div>

                    @*<label for="adType">نوع آگهی</label>
                        <div class="input-group">
                            <input type="checkbox" class="checkbox" onchange="toggleMozayede();" />
                        </div>*@
                </div>
            </div>
            <script>
                function toggleMozayede(ch) {
                    // $("#moz").hidden = !$("#moz").hidden;
                    document.getElementById("moz").style.display = ch.checked ? "flex" : "none";
                    document.getElementById("adPriceLabel").innerHTML = ch.checked ? "قیمت پایه مزایده" : "قیمت";
                }

                function toggleTabligh(ch) {
                    $("#adTabligh").val(ch.checked);
                }
            </script>
            <div id="moz" class="row" style="display: none;">
                <div class="col-6">
                    <label for="adDeadlineData">تاریخ اتمام مزایده</label>
                    <div class="form-group">
                        <input class="form-control" type="date" name="DeadlineDate" />
                    </div>
                </div>
                <div class="col-6">
                    <label for="adDeadlineTime">ساعت اتمام مزایده</label>
                    <div class="form-group">
                        <input class="form-control" type="time" name="DeadlineTime" />
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group">
                    <label for="adDescription">توضیحات آگهی</label>
                    <textarea class="form-control" rows="5" name="Description"></textarea>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col">
                    <label for="city">شهر</label>
                    <div class="input-group">
                        <select class="browser-default custom-select" id="city" name="City">
                            <option value="" selected disabled>شهر خود را انتخاب کنید</option>
                            @{
                                var cities = Bekhar.Models.Utility.GetAllCities();
                            }
                            @foreach (var city in cities)
                            {
                                <option value="@city">@city</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="col">
                    <label for="zone">محله</label>
                    <div class="input-group">
                        <input type="text" id="zone" name="Location" class="form-control" placeholder="نام محله خود را وارد کنید" />
                    </div>
                </div>
                <!--
                <div class="col">
                    <label for="zone">شماره موبایل</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="Mobile" placeholder="000000000" style="direction:ltr;" disabled>
                        <div class="input-group-append">
                            <span class="input-group-text">09</span>
                        </div>

                    </div>
                </div>
                    -->

            </div>
            <div class="row">
                <div class="col-5">
                    <label for="adPrice" id="adPriceLabel">قیمت</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="Price" id="adPrice" />
                        <div class="input-group-append">
                            <span class="input-group-text">تومان</span>
                        </div>
                    </div>
                </div>
                <div class="col-7">
                    <label for="inputGroupFile01">عکس</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01"><i class="fas fa-upload"></i></span>
                        </div>
                        <div class="custom-file">
                            <input type="file" name="myfile" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label text-muted" for="inputGroupFile01">عکس مرتبط با آگهی را انتخاب کنید . . .</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mr-1" style="direction:ltr;">
                <input type="submit" class="btn deep-orange" value="ثبت آگهی" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bekhar/Views/Kala/Delete.cshtml
@model Bekhar.Models.Kala

@{
    Page.Title = "حذف کالا";
}

<h3>آیا مطمئنید که می خواهید حذف کنید؟</h3>
<div>
    <h4>Kala</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Bekhar/Views/Kala/Details.cshtml
@using Bekhar.Models
@model Bekhar.Models.Kala

@{
    Page.Title = "نمایش کالا";
}

<div class="container pt-3 mb-5">
    <div class="row ">
        <div class="col-6">
            <h2>@Model.Name</h2>
            <p>تاریخ: @Model.CreationTime.GetPersianStr()</p>
            @if(Model.DataType == ModelType.Mozayede)
            {
            <span id="countdown">
                زمان باقی مانده از مزایده: 
                <span id="sec">

                </span>
                :
                <span id="min">

                </span>
                :
                <span id="hour">

                </span>
                <span id="day">

                </span>
            </span>
            }
            <table class="table">


                <tr>
                    <td class="text-center font-weight-bold">دسته بندی</td>
                    <td> @Model.Category</td>
                </tr>

                <tr>
                    <td class="text-center font-weight-bold">محل</td>
                    <td>@Model.City - @Model.Location</td>
                </tr>
                <tr>
                    <td class="text-center font-weight-bold">قیمت</td>
                    <td>@Utility.GetCommaSeperatedNumber(Model.Price.ToString()) <span class="font-weight-bold">تومان</span></td>
                </tr>
                <tr>
                    <td class="text-center font-weight-bold">موبایل</td>
                    <td> @Model.Mobile </td>
                </tr>

                <tr>
                    <td class="text-center font-weight-bold">ایمیل</td>
                    <td> @Model.Email</td>
                </tr>

            </table>
            <p><span class="font-weight-bold"> توضیحات: </span> 
                @Model.Description
            </p>
            <div class="text-center">
                <a href="/Kharids/Create?KalaId=@(Model.Id)" class="btn btn-success">خرید</a>
            </div>
            
        </div>
        <div class="col-6 ">
            <img src="https://via.placeholder.com/450" class="rounded" style="width:inherit;">
            <p class="text-center pt-2 grey-text">غوره هیچگونه مسوولیتی ندارد</p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        setInterval(function time() {
            var d = new Date(@Model.DeadlineTimeStamp) - new Date();
            var days = d.days;// @(Model.Deadline?.Subtract(DateTime.Now).Days);
            var hours = d.hours; // @(Model.Deadline?.Subtract(DateTime.Now).Hours);
            var min = d.min;// @(Model.Deadline?.Subtract(DateTime.Now
                               ).Minutes);
            if ((min + '').length == 1) {
                min = '0' + min;
            }
            var sec = d.sec;// @(Model.Deadline?.Subtract(DateTime.Now).Seconds);
            if ((sec + '').length == 1) {
                sec = '0' + sec;
            }
            $("#countdown #day").html(days);
            jQuery('#countdown #hour').html(hours);
            jQuery('#countdown #min').html(min);
            jQuery('#countdown #sec').html(sec);
        }, 1000);
    });
</script>

Bekhar/Views/Kala/Index.cshtml
@using Bekhar.Models
@model IEnumerable<Bekhar.Models.Kala>

@{
    Page.Title = "آگهی های من";
}

@if(Model.Count() > 0)
{
    <div class="wrapper">
        <div class="container-fluid pt-4 px-4 yekan">
            <div class="card-deck ml-5">
                @foreach (var kala in Model)
                {
                    <div class="card my-3" style="max-width:300px;">
                        <div class="view">
                            <img src="https://via.placeholder.com/300" class="card-img-top" alt="" style="max-height:300px;">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">@kala.Name</h4>
                            <p class="card-text">@Utility.GetSummery(kala.Description)</p>
                        </div>
                        <div class="card-footer p-1 text-center" style="background:#FFF; border-top:none;">
                            <div class="mr-auto my-auto pl-3 deep-orange-text">@Utility.GetCommaSeperatedNumber(kala.Price.ToString()) <span class="font-weight-bold">تومان</span></div>
                        </div>
                        <div class="card-footer p-1 d-flex justify-content-center">
                            @Html.ActionLink("مشاهده کالا", "Details", new { id = kala.Id }, new { @class = "btn btn-primary font-weight-bold" })
                        
                            @*@Html.ActionLink("حذف کالا", "Delete", new { id = kala.Id }, new { @class= "btn btn-danger font-weight-bold" })*@
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal" data-id="@kala.Id">
                                حذف کالا <i class="fas fa-trash ml-2"></i>
                            </button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">حذف کالا</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    آیا از حذف کالا زیر مطمئنید؟
                </div>
                <div class="modal-footer">
                    
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal">خیر</button>
                    @using (Html.BeginForm("Delete", "Kala", FormMethod.Post, new { @id = "delForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <input name="id" type="hidden" value="" id="delID" />
                        <button type="button" class="btn btn-danger" onclick="document.getElementById('delForm').submit();">حذف<i class="fas fa-trash ml-2"></i></button>
                    }
                </div>
            </div>
        </div>
    </div>

    <script>
        $('#exampleModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var recipient = button.data('id') // Extract info from data-* attributes
            var modal = $(this)
            $('#delID').val(recipient)
            $('#delForm').attr('action', "/Kala/Delete/" + recipient);
            // modal.find('.modal-body input').val(recipient)
        })
    </script>
}
else
{
    <h3 class="mx-auto text-center text-muted mt-5">کالایی برای نمایش وجود ندارد</h3>
}